Repository iNZightVIT/iNZightModules, pull requests merged in 2020-04, with the labels that each got.

#98 Module installation window
  .travis.yml
  NAMESPACE
  R/CustomModule.R
  man/InstallModules-class.Rd
Labels: enhancement

#101 Release 2.4.9
  .travis.yml
  DESCRIPTION
  Makefile
  NAMESPACE
  NEWS.Md
  R/CustomModule.R
  R/iNZightTS.R
  appveyor.yml
  man/InstallModules-class.Rd
Labels: release

#102 Release 2.4.9 into dev
  .travis.yml
  DESCRIPTION
  NEWS.Md
  appveyor.yml
Labels: release

#100 stringsAsFactors = TRUE for R 4.0.0
  NEWS.Md
  R/iNZightMaps2.R
  R/supportPlot3D.R
  tests/testthat/test_regression_survey.R
Labels: bug

#108 Fix #104
  NEWS.Md
  R/iNZightMultiRes.R
  tests/testthat/test_mr.R
Labels: bug

#112 Remove intercept option (#111)
  NEWS.Md
  R/iNZightRegression.R
  appveyor.yml
  tests/testthat/test_regression.R
Labels: enhancement
